inherits = "base16_transparent"

"comment" = {{ "{ fg = \"color8\" }" }}
"constant" = {{ "{ fg = \"color11\", modifiers = [\"bold\"] }" }}
"constant.character.escape" = {{ "{ fg = \"color13\" }" }}
"function" = {{ "{ fg = \"color9\", modifiers = [\"bold\"] }" }}
"keyword" = {{ "{ fg = \"color14\", modifiers = [\"bold\"] }" }}
"operator" = {{ "{ fg = \"color12\" }" }}
"punctuation" = {{ "{ fg = \"color15\" }" }}
"string" = {{ "{ fg = \"color10\", modifiers = [\"bold\"] }" }}
"path" = {{ "{ fg = \"color2\" }" }}
"string.regexp" = {{ "{ fg = \"color6\" }" }}
"tag" = {{ "{ fg = \"color3\", modifiers = [\"bold\"] }" }}
"type" = {{ "{ fg = \"color4\", modifiers = [\"bold\"] }" }}
"type.enum.variant" = {{ "{ fg = \"color7\", modifiers = [\"italic\"] }" }}
"variable" = {{ "{ fg = \"foreground\" }" }}
"variable.builtin" = {{ "{ fg = \"color15\", modifiers = [\"italic\"] }" }}
"variable.parameter" = {{ "{ fg = \"color5\", modifiers = [\"italic\"] }" }}
"identifier" = {{ "{ fg = \"color1\", modifiers = [\"italic\"] }" }}
"members" = {{ "{ fg = \"color7\", modifiers = [\"bold\"] }" }}

"diff.plus" = {{ "{ fg = \"color10\" }" }}
# "diff.delta" = {{ "{ fg = \"color8\", bg = \"color17\" }" }}
"diff.delta" = {{ "{ fg = \"color12\" }" }}
"diff.minus" = {{ "{ fg = \"color9\" }" }}

# "ui.background" = {{ "{ fg = \"color5\", bg = \"color0\" }" }}
"ui.cursor" =  {{ "{ fg = \"color0\", bg = \"color9\" }" }}
"ui.cursor.match" = {{ "{ fg = \"color5\", modifiers = [\"underlined\"] }" }}
"ui.cursor.primary" = {{ "{ fg = \"color0\", bg = \"color15\" }" }}
# "ui.help" = {{ "{ fg = \"foreground\", bg = \"color16\" }" }}
"ui.help" = {{ "{ fg = \"foreground\" }" }}
"ui.linenr" = {{ "{ fg = \"color8\" }" }}
# "ui.linenr.selected" = {{ "{ fg = \"color15\", bg = \"color0\" }" }}
"ui.linenr.selected" = {{ "{ fg = \"color15\" }" }}
"ui.menu" = {{ "{ fg = \"foreground\" }" }}
# "ui.menu" = {{ "{ fg = \"foreground\", bg = \"color17\" }" }}
"ui.menu.selected" = {{ "{ fg = \"foreground\", bg = \"color4\" }" }}
"ui.menu.highlighted" = {{ "{ fg = \"color6\" }" }}
# "ui.popup" = {{ "{ fg = \"foreground\", bg = \"color0\" }" }}
"ui.popup" = {{ "{ fg = \"foreground\" }" }}
# "ui.selection" = {{ "{ bg = \"color17\" }" }}
"ui.selection.primary" = {{ "{ bg = \"color4\", fg = \"color0\" }" }}
# "ui.statusline" = {{ "{ fg = \"foreground\", bg = \"color16\" }" }}
"ui.statusline" = {{ "{ fg = \"foreground\" }" }}
# "ui.statusline.inactive" = {{ "{ fg = \"color8\", bg = \"color16\" }" }}
"ui.statusline.inactive" = {{ "{ fg = \"color8\" }" }}
"ui.text" = {{ "{ fg = \"foreground\" }" }}
"ui.text.focus" = {{ "{ fg = \"color15\" }" }}
"ui.window" = {{ "{ fg = \"color5\" }" }}
"ui.virtual" = {{ "{ fg = \"color8\" }" }}
"ui.virtual.inlay-hint.parameter" = {{ "{ fg = \"color8\" }" }}
"ui.virtual.inlay-hint.type" = {{ "{ fg = \"color8\" }" }}

"error" = {{ "{ fg = \"color9\" }" }}
"warning" = {{ "{ fg = \"color11\" }" }}
"info" = {{ "{ fg = \"color12\" }" }}
"hint" = {{ "{ fg = \"color15\" }" }}
"diagnostic" = {{ "{ modifiers = [\"underlined\"] }" }}

"markup.heading" = {{ "{ fg = \"color11\", modifiers = [\"bold\"] }" }}
"markup.list" = "color15"
"markup.bold" = {{ "{ fg = \"color9\", modifiers = [\"bold\"] }" }}
"markup.italic" = {{ "{ fg = \"color7\", modifiers = [\"italic\"] }" }}
"markup.link.url" = "color12"
"markup.link.text" = "color14"
"markup.quote" = {{ "{ fg = \"color8\", modifiers = [\"italic\"] }" }}
"markup.raw" = {{ "{ fg = \"color10\" }" }}

[palette]
foreground = "{{color7}}"
color0 = "{{color0}}"
color1 = "{{color1}}"
color2 = "{{color2}}"
color3 = "{{color3}}"
color4 = "{{color4}}"
color5 = "{{color5}}"
color6 = "{{color6}}"
color7 = "{{color7}}"
color8 = "{{color8}}"
color9 = "{{color9}}"
color10 = "{{color10}}"
color11 = "{{color11}}"
color12 = "{{color12}}"
color13 = "{{color13}}"
color14 = "{{color14}}"
color15 = "{{color15}}"
# color16 = "{{background | darken(1)}}"
# color17 = "{{background | lighten(10)}}"
