theme = "wallust"

[editor]
line-number = "relative"
default-yank-register = "+"
popup-border = "all"
idle-timeout = 0
completion-trigger-len = 1
auto-format = true
color-modes = true
rainbow-brackets = true
welcome-screen = false
undercurl = true
mouse = true

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.lsp]
display-inlay-hints = true
auto-signature-help = false
# display-progress-messages = true

[icons.vcs]
enabled = true
icon = "î‚ "

[icons.mime]
enabled = true
directory = "ğŸ–¿"
rust = "ğŸ¦€"
python = "ğŸ"
go = "î˜§"
json = "î˜‹"

[icons.kind]
enabled = true

[editor.notifications]
enable = true
style = "popup"
position = "top-right"
default-timeout = 5000
padding = 0

[editor.notifications.border]
enable = true

[editor.notifications.emojis]
info = "ğŸ’¡"
warning = "âš ï¸"
error = "âŒ"
success = "âœ…"

[editor.cmdline]
style="bottom" # popup

[editor.cmdline.icons]
search = "î™„ "
general = "ï’µ "
command= "ï’µ "

[editor.bufferline]
render-mode = "always"
separator = "|"

[editor.statusline]
left = [ "mode", "read-only-indicator", "version-control", "function-name", "spinner"]
right = ["diagnostics", "register", "position", "position-percentage", "file-encoding"]

mode.normal = "N"
mode.insert = "I"
mode.select = "V"

diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]

[editor.whitespace.render]
space = "none"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.whitespace.characters]
space = "Â·"
nbsp = "â½"
nnbsp = "â£"
tab = "â†’"
newline = "â"
tabpad = "Â·" # Tabs will look like "â†’Â·Â·Â·" (depending on tab width)

[editor.indent-guides]
render = true

[editor.smart-tab]
enable = false
supersede-menu = true

[editor.file-picker]
hidden = false # enables ignoring hidden files
parents = true # enables reading ignore files from parent directories
ignore = true # enables reading .ignore files
git-ignore = true # enables reading .gitignore files
git-global = true
git-exclude = true

[keys.normal]
tab = "move_parent_node_end"
S-tab = "move_parent_node_start"
d = "delete_selection_noyank"
c = "change_selection_noyank"
A-k = "select_prev_sibling"
A-j = "select_next_sibling"

[keys.normal." "]
q = ":quit"
c = ":buffer-close"
tab = "insert_tab"
w = ":write"
"," = "code_action"
1 = ":goto-buffer 1"
2 = ":goto-buffer 2"
3 = ":goto-buffer 3"
4 = ":goto-buffer 4"
5 = ":goto-buffer 5"
6 = ":goto-buffer 6"
7 = ":goto-buffer 7"
8 = ":goto-buffer 8"
9 = ":goto-buffer 9"
0 = ":goto-buffer 0"

[keys.normal." "."g"]
g = "changed_file_picker"
b = ":! git show --no-patch --format='%%h (%%an: %%ar): %%s' $(git blame -p %{buffer_name} -L%{cursor_line},+1 | head -1 | cut -d' ' -f1)"

[keys.insert]
C-f = "goto_next_tabstop"
C-S-f = "goto_prev_tabstop"
C-l = "signature_help"

